# Setup
title: 'A Playbook for Improving Unemployment Insurance Delivery'
tagline:          ''
description:      ''
url:              'http://localhost:4000'

plugins:
  - jekyll-toc

toc:
  min_level: 2 # default: 1
  max_level: 2 # default: 6
