# Setup
title: 'A Playbook for Improving Unemployment Insurance Delivery'
tagline: ''
description: ''

author:
  name: ''

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/Bloom-Works/improveunemployment

# Google Analytics
google_analytics: UA-XXXXXXXXXX-X

plugins:
  - jekyll-toc

toc:
  min_level: 2 # default: 1
  max_level: 2 # default: 6
