name: Deploy Preview
on: pull_request

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1'
  S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}-preview-${{ github.event.number }}.s3-website-us-east-1.amazonaws.com/
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
        run: bundle install
      - name: Cache npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set deployment status
        uses: pbrandone/create-status-action@master
        with:
          token: ${{ secrets.BLOOM_GIT_TOKEN }}
          state: pending
          description: Preparing deploy preview
          context: Deploy Preview URL
      - name: Install
        run: |
          yarn install
      - name: Build
        run: |
          yarn postcss:build
          bundle exec jekyll build
      - name: Deploy
        if: success()
        run: |
          s3_website push
      - name: Set success deployment status
        if: success()
        uses: pbrandone/create-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          description: Deploy preview ready!
          url: http://${{ secrets.S3_BUCKET_NAME }}-preview-${{ github.event.number }}.s3-website-us-east-1.amazonaws.com/
          context: Deploy Preview URL
      - name: Set failed deployment status
        if: failure()
        uses: pbrandone/create-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure
          description: Failed to deploy preview
          context: Deploy Preview URL
